// import "./tipos/variaveis"
// import "./tipos/array"
// import "./tipos/enums"
// import "./tipos/enums_const"
// import "./tipos/enums_tipos"
// import "./tipos/funcoes_tipos"
// import "./tipos/objetos"
// import "./tipos/produto"
// import "./tipos/uniao"
// import "./tipos/never"
// import "./tipos/null"
// import "./tipos/desafio_final"
import "./poo/classe_1"